language: java

addons:
  sonarcloud:
    organization: "clembdx"
    token: "$SONARCLOUD_TOKEN"

jobs:
  include:
    - stage: dev
      name: Test 1
      script: ./scripts/build.sh
    - stage: ops
      name: Test 2
      script: ./script/docker.sh

branches:
  only:
    - develop

cache:
  directories:
    - $HOME/.m2

services:
  - docker

