language: java
script:
  # Test and build your app with docker
  - cd ./simple-api
  - mvn clean verify
  # Connexion à Docker
  - echo "$DOCKER_PASS" | docker login -u "DOCKER_USERNAME" password-stdin
  # Build
  - docker build -t $DOCKER_USERNAME/tp-devops.
  # Publication des images
  - docker push $DOCKER_USERNAME/tp-devops
branches:
  only:
    - develop
cache:
  directories:
    - $HOME/.m2
services:
  - docker